* Auroph Seyman XP: 1/32

** Basic attributes
Phy 5 = 4 + 1 (5 XP)
=>
Health 5

Mnt 5 = 1 + 4 (2+3+4+5 XP)
=>
Morale 5

** Optional attributes

*** Spirituality 5 (1: 1+2 | 3+4+5)
=>
Enlightment 5

Spirituality defensive bonuses require not wearing armor. As long as character is wearing armor,
those options are disabled.

**** Open hand (·)
Spiritualist knows martial arts: he can use parry mode and doesn't get penalties in clashes made in unarmed combat.
**** Flurry of blows (··)
Martial artist gets an additional physical development roll on aggressive clashes in combat,
he can attack at will in defensive mode, he can attack in parry mode as though it was defensive mode.
**** Sundering strike (··)
Martial artist, faced by control weapon wielders has the only option — to sunder they weapons.
Sundering strike allows using unarmed attacks to sunder weapons.
**** Graceful spirit (···)
Spiritualist gets +1 roll on defensive clashes in combat.
**** Spiritblood (···)
After spiritualist is dealt damage for the first time during a day, spiritualist can choose to use his enlightment points instead of health points for the rest of the day. 
**** Lay on hands (···)
Spiritualist can heal one point of health damage to a willing living creature touched by spending one point of enlightment.
**** Bodyfree (····)
After spiritualist is dealt damage, spiritualist can choose to use his enlightment points instead of health points for the rest of the day.
**** Harmony (····)
If your harmony is greater than one, you get +1 roll bonus to all your attack and defense clashes in combat.
**** Tendrils of spiritblood (····)
All your allies get spiritblood but instead of their enlighment scores, they use yours.
**** Slow fall 60 ft. (····)
Ditto.
**** Abundant step (·····)
Dimension door, once / day.
**** Perfect self (·····)
Spiritualist reaches perfection becoming one with the spirit. Treat him as outsider rather than his basic type.
He gets damage reduction 1/magic.
**** Tendrils of harmony (·····)
If each of your allies is greater than one, he or she gets a +1 roll bonus to all his or her attack and defense clashes in combat.
**** Empty Body (·····)
As an interrupt, assume etheral form for one round. Once / day.
**** Tongue of the Sun and Moon (·····)
You can understand and speak to every living creature.
**** Ki strike (M ··)
Treat your fists as a +1 magical weapon. (+1 roll in attack clashes in combat)
**** Tranquility (M ···)
Instead of +1 harmony bonus, apply bonus equals to your harmony value.
**** Magic fist (M ····)
In aggressive mode, spiritualist capable of casting magic can choose to cast an offensive spell as a part of unarmed attack.
**** Diamond body (M ·····)
Once a day, you may perform a ritual to apply a spell to yourself. Its effect end after you lose a combat clash.


*** Elementalism 2 (1: 2+2)
=>
Mana 2

**** Spontaneous casting (·)
Caster can use not only morale points but also mana points to spontaneously cast spells.
**** Point control: Earth (··)
Choose Earth elemental blast or Grease —
   
   Earth elemental blast:
   Clash elementalism vs target's physical development. If you win, target is stunned for a full round action.
   Range: Medium
   Target: Living creature, or undead, or outsider from The Elemental Plane of Air. 
   Duration: Instanteneous
   Clash: Elementalism vs Phy

   Grease:
   Ten foot square is covered in grease. 
   Every character that starts an action in there clashes physical development vs your elementalism. 
   If he doesn't win — he falls prone. Greased terrain is considered to be difficult. 
   Characters that are in the area of effect of grease as it's cast clash and fall prone if they didn't win.
   Range: Close (25 ft. + 5 ft / level)
   Clash: Elementalism vs Phy, multiple

**** Protection spells: Earth (··)
Choose Virtue or Stoneskin —

   Virtue: target gets one temporary point of health.
   Target: Willing living creature, or undead, or outsider from The Element Plane of Earth.
   Duration: 1 minute / level
   Range: Touch
   Clash: —

   Stoneskin: if more than one damage is dealt to a target by an effect, one damage is dealt instead.
   Target: Willing living creature, or undead, or outsider from The Element Plane of Earth.
   Duration: 1 minute / level
   Range: Close (25 ft. + 5. ft / level)
   Clash: —

*** Equipment

Ring of burrow: on any material plane, you may obtain burrow speed
equal to character's speed once a day for amount of minutes equal to
your mana (minium 1).  On Elemental Plane of Earth the effect is
permanent.

Wealth: 3
