* Kæl Limidiel XP: 2/32

** Basic attributes

Phy 3 (XP: 3+4)
=> 
Health: 4

Men 5 (XP: 4+5)
=>
Morale: 5

** Druidism 4 (1+2 | XP: 3+4)
=>
Essence: 4

**** Spontaneous (·)
**** Basic life magic (··)

 - Cure wounds:
   Spend one essence point: restore one health point.
   Range: touch
   Target: willing living creature
   Clash: —

 - Nature's Ally I: 
   Summon 2/1 medium creature
   Range: close (25 + 5)
   Target: ground
   Clash: —

**** Basic tactical magic (··)

 - Obscuring mist:
   A misty vapor arises around you. It is stationary once created. The
   vapor obscures all sight, including darkvision, beyond 5 feet. A
   creature 5 feet away has concealment (attacks have a 20% miss
   chance). Creatures farther away have total concealment (50% miss
   chance, and the attacker cannot use sight to locate the target).
   A moderate wind (11+ mph), such as from a gust of wind spell,
   disperses the fog in 4 rounds. A strong wind (21+ mph) disperses
   the fog in 1 round. A fireball, flame strike, or similar spell
   burns away the fog in the explosive or fiery spell’s area. A wall
   of fire burns away the fog in the area into which it deals damage.
   Range: 0
   Target: —
   Effect: Cloud spreads in 20-ft. radius from you, 20 ft. high
   Duration: 1 min./level
   Clash: —
   Saving throw: None

 - Spider climb: 
   The subject can climb and travel on vertical surfaces
   or even traverse ceilings as well as a spider does. The affected
   creature must have its hands free to climb in this manner. The
   subject gains a climb speed of 20 feet; furthermore, it need not
   make Climb checks to traverse a vertical or horizontal surface
   (even upside down). A spider climbing creature retains its
   Dexterity bonus to Armor Class (if any) while climbing, and
   opponents get no special bonus to their attacks against it. It
   cannot, however, use the run action while climbing.
   Target: willing target
   Range: touch
   Duration: 1 min./level

**** Wrath of nature (···)

  - Sleet Storm
  Conjuration (Creation) [Cold]
  Level: 	Drd 3, Sor/Wiz 3
  Components: 	V, S, M/DF
  Casting Time: 1 standard action
  Range: 	Long (400 ft. + 80 ft./level)
  Area: 	Cylinder (40-ft. radius, 20 ft. high)
  Duration: 	1 round/level
  Clash:        None

  Driving sleet blocks all sight (even darkvision) within it and causes
  the ground in the area to be icy. A creature can walk within or
  through the area of sleet at half normal speed with a DC 10 Balance
  check. Failure means it can’t move in that round, while failure by 5
  or more means it falls (see the Balance skill for details).  The sleet
  extinguishes torches and small fires.

  - Call Lightning
    Evocation [Electricity]
    Level: 	Drd 3
    Components: 	V, S
    Casting Time: 	1 round
    Range: 	Medium (100 ft. + 10 ft./level)
    Effect: 	One or more 30-ft.-long vertical lines of lightning
    Duration: 	1 min./level
    Clash: Druidism vs physical

    Immediately upon completion of the spell, and once per round
    thereafter, you may call down a 5-foot-wide, 30-foot-long,
    vertical bolt of lightning that deals electricity damage. The bolt
    of lightning flashes down in a vertical stroke at whatever target
    point you choose within the spell’s range (measured from your
    position at the time). Any creature in the target square or in the
    path of the bolt is affected.  You need not call a bolt of
    lightning immediately; other actions, even spellcasting, can be
    performed. However, each round after the first you may use a
    standard action (concentrating on the spell) to call a bolt. You
    may call a total number of bolts equal to your caster level
    (maximum 10 bolts).  If you are outdoors and in a stormy area—a
    rain shower, clouds and wind, hot and cloudy conditions, or even a
    tornado (including a whirlwind formed by a djinni or an air
    elemental of at least Large size)—each bolt deals gets r1 (replace
    one roll with a success). This spell functions indoors or
    underground but not underwater.

**** Healing (···)
     Remove Disease and Neutralize Poison.

**** Advanced Animalism (···)
     
     Magic Fang: willing animal's natural attacks deal extra point of damage.
     
     Dominate Animal
     Enchantment (Compulsion) [Mind-Affecting]
     Level: 	Animal 3, Drd 3
     Components: 	V, S
     Casting Time: 	1 round
     Range: 	Close (25 ft. + 5 ft./2 levels)
     Target: 	One animal
     Duration: 	1 round/level
     Clash:     Druidism vs Mental
     
     You can enchant an animal and direct it with simple commands such
     as “Attack,” “Run,” and “Fetch.” Suicidal or self-destructive
     commands (including an order to attack a creature two or more
     size categories larger than the dominated animal) are simply
     ignored.
     
     Dominate animal establishes a mental link between you and the
     subject creature. The animal can be directed by silent mental
     command as long as it remains in range. You need not see the
     creature to control it. You do not receive direct sensory input
     from the creature, but you know what it is experiencing. Because
     you are directing the animal with your own intelligence, it may
     be able to undertake actions normally beyond its own
     comprehension. You need not concentrate exclusively on
     controlling the creature unless you are trying to direct it to do
     something it normally couldn’t do. Changing your instructions or
     giving a dominated creature a new command is the equivalent of
     redirecting a spell, so it is a move action.

**** Freedom (····)

     Air Walk: Subject treads on air as if solid (climb at 45-degree angle).

     Freedom of Movement: Subject moves normally despite impediments.

** Arcanism 4 (2+2 | XP: 3+4)
=>
Arcane: 4
